language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install libboost-system-dev libboost-thread-dev

script:
  - cd build
  - cmake .
  - make
  - ./json_test

notifications:
  irc: "irc.freenode.org#sirikata"
