stages:
  - build
  - check

variables:
  BUILD_DIR: _build
  DRAKE_DEBUG_BACKTRACE: "1"
  DRAKE_EXPLAIN: "1"
  INSTALL_DIR: _install
  PROJECT: "elle"
  PYTHONUNBUFFERED: "1"
  GIT_SUBMODULE_STRATEGY: "none"

before_script:
  - NPROC=$(nproc)

build:
  stage: build
  image: registry.gitlab.gruntech.org/mefyl/elle/trusty-ci
  script:
    - farm/configure --arch x86_64 --os xenial --compiler gcc4 --project $PROJECT --source-dir "$CI_PROJECT_DIR" --build-dir "$BUILD_DIR" --install-dir "$INSTALL_DIR"
    - ccache --set-config=cache_dir="$CI_PROJECT_DIR/.ccache"
    - ccache -z
    - cd "$BUILD_DIR" && python3 drake -j $NPROC //build
    - ccache -s
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}"
    paths:
      - _build
  cache:
    paths:
      - .ccache

examples:
  stage: check
  image: registry.gitlab.gruntech.org/mefyl/elle/trusty-ci
  script:
    - ccache --set-config=cache_dir="$CI_PROJECT_DIR/.ccache"
    - ccache -z
    - cd "$BUILD_DIR" && python3 drake -j $NPROC //examples
    - ccache -s
  dependencies:
    - build
  cache:
    paths:
      - .ccache

check:
  stage: check
  image: registry.gitlab.gruntech.org/mefyl/elle/trusty-ci
  script:
    - ccache --set-config=cache_dir="$CI_PROJECT_DIR/.ccache"
    - ccache -z
    - cd "$BUILD_DIR" && python3 drake -j $NPROC //check
    - ccache -s
  dependencies:
    - build
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}"
    paths:
      - _build
  cache:
    paths:
      - .ccache
